const WRONG_STORAGE_KEY='cppg_wrong_answers';
let currentQuizSet=[],currentIndex=0,userAnswers={},bookmarked={},timerInterval=null,secondsLeft=0,timeSpentSeconds=0,quizStartedAt=0;
const $=id=>document.getElementById(id);
function getWrongList(){try{return JSON.parse(localStorage.getItem(WRONG_STORAGE_KEY)||'[]')}catch{return[]}}
function saveWrongList(list){localStorage.setItem(WRONG_STORAGE_KEY,JSON.stringify([...new Set(list)]));updateWrongCount()}
function updateWrongCount(){$('wrong-count').innerText=getWrongList().length}
function shuffle(arr){const a=[...arr];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function startQuiz(count){if(!QUESTION_BANK?.length)return alert('문제 데이터가 없습니다.');currentQuizSet=shuffle(QUESTION_BANK).slice(0,Math.min(count,QUESTION_BANK.length));initQuizState(count===100?120*60:15*60)}
function startWrongQuiz(){const ids=getWrongList();if(!ids.length)return alert('저장된 오답이 없습니다.');currentQuizSet=shuffle(QUESTION_BANK.filter(q=>ids.includes(q.id)));initQuizState(Math.max(15*60,Math.ceil(currentQuizSet.length*90)))}
function initQuizState(limit){currentIndex=0;userAnswers={};bookmarked={};secondsLeft=limit;timeSpentSeconds=0;quizStartedAt=Date.now();$('homeView').classList.add('hidden');$('resultView').classList.add('hidden');$('quizView').classList.remove('hidden');$('quizHeaderInfo').classList.remove('hidden');$('totalQNum').innerText=currentQuizSet.length;$('totalCountDisplay').innerText=currentQuizSet.length;buildOMRGrid();renderQuestion();updateAnsweredCount();startTimer();window.scrollTo({top:0,behavior:'smooth'})}
function startTimer(){clearInterval(timerInterval);updateTimerDisplay();timerInterval=setInterval(()=>{secondsLeft--;timeSpentSeconds++;updateTimerDisplay();if(secondsLeft<=0){clearInterval(timerInterval);alert('시험 시간이 종료되어 자동으로 답안을 제출합니다.');submitQuiz()}},1000)}
function updateTimerDisplay(){const m=Math.floor(Math.max(0,secondsLeft)/60),s=Math.max(0,secondsLeft)%60;$('timer').innerText=`${String(m).padStart(2,'0')}:${String(s).padStart(2,'0')}`}
function buildOMRGrid(){const g=$('omrGrid');g.innerHTML='';currentQuizSet.forEach((_,i)=>{const b=document.createElement('button');b.id=`omr-btn-${i}`;b.innerText=i+1;b.onclick=()=>jumpToQuestion(i);b.className='h-8 rounded font-semibold text-xs border border-slate-700 bg-slate-900 text-slate-400';g.appendChild(b)})}
function renderQuestion(){const q=currentQuizSet[currentIndex];if(!q)return;$('currentQNum').innerText=currentIndex+1;$('questionCategory').innerText=q.category||'CPPG';$('questionText').innerText=`${currentIndex+1}. ${q.question}`;const box=$('optionsContainer');box.innerHTML='';q.options.forEach((opt,i)=>{const selected=userAnswers[currentIndex]?.choice===i;const d=document.createElement('button');d.type='button';d.onclick=()=>selectOption(i);d.className=`option-card w-full p-4 rounded-xl border text-left flex items-start gap-3 ${selected?'bg-indigo-600/20 border-indigo-500 text-white shadow-md':'bg-slate-900/60 border-slate-700/80 text-slate-300 hover:border-slate-600'}`;d.innerHTML=`<span class="w-7 h-7 rounded-full border flex items-center justify-center text-xs font-bold shrink-0 ${selected?'border-indigo-400 bg-indigo-500 text-white':'border-slate-600 text-slate-400'}">${i+1}</span><span class="text-sm leading-relaxed">${escapeHtml(opt)}</span>`;box.appendChild(d)});$('prevBtn').disabled=currentIndex===0;$('nextBtn').innerHTML=currentIndex===currentQuizSet.length-1?'제출/결과 <i class="fa-solid fa-check ml-2"></i>':'다음 문제 <i class="fa-solid fa-chevron-right ml-2"></i>';$('bookmarkIcon').className=bookmarked[currentIndex]?'fa-solid fa-bookmark text-amber-400 mr-1':'fa-regular fa-bookmark mr-1';updateOMRGrid()}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function selectOption(i){userAnswers[currentIndex]={choice:i};renderQuestion();updateAnsweredCount()}
function toggleBookmark(){bookmarked[currentIndex]=!bookmarked[currentIndex];renderQuestion()}
function navigateQuestion(dir){const n=currentIndex+dir;if(n<0)return;if(n>=currentQuizSet.length){submitQuizConfirm();return}currentIndex=n;renderQuestion();window.scrollTo({top:0,behavior:'smooth'})}
function jumpToQuestion(i){currentIndex=i;renderQuestion();window.scrollTo({top:0,behavior:'smooth'})}
function updateOMRGrid(){currentQuizSet.forEach((_,i)=>{const b=$(`omr-btn-${i}`);if(!b)return;let c='bg-slate-900 text-slate-400 border-slate-700';if(i===currentIndex)c='bg-slate-800 text-white border-2 border-indigo-400 ring-2 ring-indigo-500/20';else if(bookmarked[i])c='bg-amber-500/20 text-amber-300 border-amber-500/50';else if(userAnswers[i])c='bg-indigo-600 text-white border-indigo-500';b.className=`h-8 rounded text-xs font-semibold flex items-center justify-center ${c}`})}
function updateAnsweredCount(){$('answeredCount').innerText=Object.keys(userAnswers).length}
function submitQuizConfirm(){const unanswered=currentQuizSet.length-Object.keys(userAnswers).length;if(unanswered&&!confirm(`아직 풀지 않은 문제가 ${unanswered}개 있습니다.\n정말 제출하시겠습니까?`))return;if(!unanswered&&!confirm('답안을 제출하시겠습니까?'))return;submitQuiz()}
function submitQuiz(){clearInterval(timerInterval);$('quizView').classList.add('hidden');$('quizHeaderInfo').classList.add('hidden');$('resultView').classList.remove('hidden');let correct=0;const wrong=getWrongList();currentQuizSet.forEach((q,i)=>{const ok=userAnswers[i]?.choice===q.answer;if(ok){correct++;}else if(!wrong.includes(q.id))wrong.push(q.id)});const answeredIds=new Set(currentQuizSet.filter((q,i)=>userAnswers[i]?.choice===q.answer).map(q=>q.id));saveWrongList(wrong.filter(id=>!answeredIds.has(id)));const pct=Math.round(correct/currentQuizSet.length*100);$('scoreText').innerText=`${pct}점`;$('correctCountText').innerText=`${correct} / ${currentQuizSet.length}`;$('accuracyText').innerText=`${pct}%`;const elapsed=Date.now()-quizStartedAt;const spent=Math.min(timeSpentSeconds,Math.floor(elapsed/1000));$('timeTakenText').innerText=`${String(Math.floor(spent/60)).padStart(2,'0')}:${String(spent%60).padStart(2,'0')}`;const badge=$('scoreBadge');badge.className=`inline-flex px-4 py-1.5 rounded-full text-xs font-bold mb-3 ${pct>=60?'bg-emerald-500/20 text-emerald-400 border border-emerald-500/30':'bg-rose-500/20 text-rose-400 border border-rose-500/30'}`;badge.innerHTML=pct>=60?'<i class="fa-solid fa-circle-check mr-1"></i>합격권 달성':'<i class="fa-solid fa-circle-xmark mr-1"></i>합격 점수 미달';renderReviewCards('all');window.scrollTo({top:0,behavior:'smooth'})}
function renderReviewCards(filter){const c=$('reviewContainer');c.innerHTML='';$('filterAllBtn').className=filter==='all'?'px-3 py-1.5 bg-indigo-600 rounded-md':'px-3 py-1.5 bg-slate-700 rounded-md';$('filterWrongBtn').className=filter==='wrong'?'px-3 py-1.5 bg-indigo-600 rounded-md':'px-3 py-1.5 bg-slate-700 rounded-md';currentQuizSet.forEach((q,i)=>{const choice=userAnswers[i]?.choice,isCorrect=choice===q.answer;if(filter==='wrong'&&isCorrect)return;const card=document.createElement('div');card.className=`p-5 rounded-xl border ${isCorrect?'bg-slate-900/40 border-slate-700':'bg-rose-950/10 border-rose-900/50'}`;let opts='';q.options.forEach((o,j)=>{let cls='bg-slate-900/60 border-slate-800 text-slate-400',tag='';if(j===q.answer){cls='bg-emerald-950/30 border-emerald-600/50 text-emerald-300 font-semibold';tag='<span class="ml-auto text-xs text-emerald-400">정답</span>'}else if(j===choice&&!isCorrect){cls='bg-rose-950/40 border-rose-600/50 text-rose-300 font-semibold';tag='<span class="ml-auto text-xs text-rose-400">내 답안</span>'}opts+=`<div class="p-3 rounded-lg border text-sm flex items-center ${cls}"><span class="font-bold mr-2">${j+1}.</span><span>${escapeHtml(o)}</span>${tag}</div>`});card.innerHTML=`<div class="flex justify-between pb-3 mb-3 border-b border-slate-700"><span class="text-xs font-semibold text-slate-300">문제 ${i+1} · ${escapeHtml(q.category||'CPPG')}</span><span class="text-xs font-bold ${isCorrect?'text-emerald-400':'text-rose-400'}">${isCorrect?'✓ 정답':'✕ 오답'}</span></div><h4 class="text-sm sm:text-base font-bold mb-4">${escapeHtml(q.question)}</h4><div class="space-y-2 mb-4">${opts}</div><div class="p-4 bg-indigo-950/20 border border-indigo-500/20 rounded-lg text-sm text-indigo-200 leading-relaxed"><b class="text-indigo-400"><i class="fa-solid fa-lightbulb mr-1"></i>상세 해설</b><div class="mt-1">${escapeHtml(q.explanation||'해설이 등록되지 않은 문제입니다.')}</div></div>`;c.appendChild(card)});if(!c.children.length)c.innerHTML='<div class="text-center py-10 text-slate-400"><i class="fa-solid fa-circle-check text-3xl text-emerald-400 mb-2 block"></i>틀린 문제가 없습니다!</div>'}
function filterReview(t){renderReviewCards(t)}
function restartQuiz(){showMenu()}
function showMenu(){clearInterval(timerInterval);$('resultView').classList.add('hidden');$('quizView').classList.add('hidden');$('quizHeaderInfo').classList.add('hidden');$('homeView').classList.remove('hidden');updateWrongCount()}
function exitQuiz(){if(confirm('진행중인 시험을 종료하시겠습니까?'))showMenu()}
document.addEventListener('DOMContentLoaded',()=>{$('total-db-count').innerText=QUESTION_BANK.length;updateWrongCount()});
